# SONOS CONSTANTS
STATE_PLAYING = "PLAYBACK_STATE_PLAYING"
STATE_IDLE= "PLAYBACK_STATE_IDLE"
STATE_PAUSED = "PLAYBACK_STATE_PAUSED"

PLAYBACK_STATE_HDMI = "linein.homeTheater.hdmi"
PLAYBACK_STATE_STATION = "station"
PLAYBACK_STATE_SPOTIFY = ""